[package]
name = "library-rs"
version = "0.1.0"
authors = ["hayatroid <hayatroid@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.3.6"
dp = { path = "crates/dp" }
